apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: polymarket-bot-strip-api-bot
  labels:
    app.kubernetes.io/name: polymarket-bot
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: capitonic-platform
    app.kubernetes.io/managed-by: Helm
    capitonic.io/environment: dev
spec:
  stripPrefix:
    prefixes: [/api/bot]
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polymarket-bot
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-polymarket-bot-strip-api-bot@kubernetescrd
  labels:
    app.kubernetes.io/name: polymarket-bot
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: capitonic-platform
    app.kubernetes.io/managed-by: Helm
    capitonic.io/environment: dev
spec:
  ingressClassName: traefik
  rules:
    - host: localhost
      http:
        paths:
          - path: /api/bot
            pathType: Prefix
            backend:
              service:
                name: polymarket-bot
                port: {name: http}
