apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: capitonic-platform
    app.kubernetes.io/managed-by: Helm
    capitonic.io/environment: dev
    capitonic.io/rollout-domain: monitoring
data:
  config.alloy: |-
{{ .Files.Get "assets/config.alloy" | nindent 4 }}
