apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: capitonic-platform
    capitonic.io/environment: {{ .Values.environment | quote }}
data:
  config.yml: |-
    tunnel: {{ required "cloudflared tunnelId is required" .Values.tunnelId | quote }}
    credentials-file: /etc/cloudflared-credentials/credentials.json
    ingress:
      - hostname: {{ .Values.hostname | quote }}
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          originServerName: {{ .Values.hostname | quote }}
      - service: http_status:404
