{{- if .Values.apiIngress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: prometheus-strip-api-metrics
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: capitonic-platform
    app.kubernetes.io/managed-by: Helm
    capitonic.io/environment: {{ $.Values.environment | quote }}
spec:
  stripPrefix:
    prefixes: [/api/metrics]
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-prometheus-strip-api-metrics@kubernetescrd
{{- if .Values.apiIngress.tls.enabled }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
{{- else }}
    traefik.ingress.kubernetes.io/router.entrypoints: web
{{- end }}
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: capitonic-platform
    app.kubernetes.io/managed-by: Helm
    capitonic.io/environment: {{ $.Values.environment | quote }}
spec:
  ingressClassName: traefik
{{- if .Values.apiIngress.tls.enabled }}
  tls:
    - hosts: [{{ .Values.apiIngress.host | quote }}]
      secretName: {{ .Values.apiIngress.tls.secretName | quote }}
{{- end }}
  rules:
    - host: {{ .Values.apiIngress.host | quote }}
      http:
        paths:
          - path: /api/metrics
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port: {name: http}
{{- end }}
