apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: capitonic-platform
    app.kubernetes.io/managed-by: Helm
    capitonic.io/environment: {{ $.Values.environment | quote }}
    capitonic.io/rollout-domain: monitoring
spec:
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 9090
      targetPort: http
