apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: grafana-strip-monitor
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: capitonic-platform
    app.kubernetes.io/managed-by: Helm
    capitonic.io/environment: dev
spec:
  stripPrefix:
    prefixes: [/monitor]
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-grafana-strip-monitor@kubernetescrd
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: capitonic-platform
    app.kubernetes.io/managed-by: Helm
    capitonic.io/environment: dev
spec:
  ingressClassName: traefik
  rules:
    - host: localhost
      http:
        paths:
          - path: /monitor
            pathType: Prefix
            backend:
              service:
                name: grafana
                port: {name: http}
