apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: capitonic-platform
    app.kubernetes.io/managed-by: Helm
    capitonic.io/environment: {{ $.Values.environment | quote }}
    capitonic.io/rollout-domain: monitoring
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storage.className | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
