image: capitonic/ingester:v1.2.1-local.4
imageDigest: sha256:777ba3da56ebca8a7c924754f6274365cdac5e801013f526e5636f03abe8214a
gitRevision: 2c92345ec6029882f0eaf1188880821a919815c1
deploymentId: capitonic-k3s-dev
master:
  replicaCount: 1
  resources:
    requests: {cpu: 50m, memory: 128Mi}
    limits: {cpu: 500m, memory: 512Mi}
worker:
  replicaCount: 1
  resources:
    requests: {cpu: 100m, memory: 256Mi}
    limits: {cpu: 750m, memory: 1Gi}
workerScaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 14
archiveStorage:
  path: /Volumes/docker-data/polymarket-bot
  nodeName: lima-rancher-desktop
  size: 300Gi
  runAsUser: 501
  runAsGroup: 1000
