image: capitonic/ingester:v1.3.0-rc.0
environment: development
imagePullPolicy: Never
imagePullSecrets: []
imageDigest: sha256:450fbac8eb8c0e942d115856009c8bc2859b2e67507104b4fa07393471ad5960
gitRevision: 633b5e897a365e9444b14ce9ce4b3d522e0b5fc2
deploymentId: capitonic-k3s-dev
master:
  replicaCount: 1
  resources:
    requests: {cpu: 50m, memory: 128Mi}
    limits: {cpu: 500m, memory: 512Mi}
worker:
  replicaCount: 1
  resources:
    requests: {cpu: 100m, memory: 256Mi}
    limits: {cpu: 750m, memory: 1Gi}
workerScaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 14
archiveStorage:
  type: local
  path: /Volumes/docker-data/polymarket-bot
  nodeName: lima-rancher-desktop
  size: 300Gi
  runAsUser: 501
  runAsGroup: 1000
apiIngress:
  enabled: true
  host: localhost
  tls:
    enabled: false
    secretName: grafana-tls
externalSecrets:
  enabled: false
credentialRevisions: {}
