image: capitonic/ingester:v1.3.0-local.1
environment: development
imagePullPolicy: Never
imagePullSecrets: []
imageDigest: sha256:9eba20ca179c240af6a01448b518c6fc96702461ce7472f1919c5fb81d85d397
gitRevision: 7ff2b1d281b349f21a91e1e9abf3456c65227c6a
deploymentId: capitonic-k3s-dev
master:
  replicaCount: 1
  resources:
    requests: {cpu: 50m, memory: 128Mi}
    limits: {cpu: 500m, memory: 512Mi}
worker:
  replicaCount: 1
  resources:
    requests: {cpu: 100m, memory: 256Mi}
    limits: {cpu: 750m, memory: 1Gi}
workerScaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 14
archiveStorage:
  type: local
  path: /Volumes/docker-data/polymarket-bot
  nodeName: lima-rancher-desktop
  size: 300Gi
  runAsUser: 501
  runAsGroup: 1000
apiIngress:
  enabled: true
  host: localhost
  tls:
    enabled: false
    secretName: grafana-tls
externalSecrets:
  enabled: false
credentialRevisions: {}
