environment: production
imagePullPolicy: IfNotPresent
imagePullSecrets: []
storage:
  className: local-path
  size: 5Gi
apiIngress:
  enabled: true
  host: monitor.capitonic.com
  tls:
    enabled: true
    secretName: grafana-tls
