environment: production
image: cloudflare/cloudflared:2025.8.1@sha256:b77d84e8704db38db22c22661cf7e56468c526e3a6a5fe9c8b7c151452fa1472
imagePullPolicy: IfNotPresent
imagePullSecrets: []
tunnelId: ""
sshHostname: ssh.capitonic.com
opsHostname: ""
replicaCount: 1
resources:
  requests: {cpu: 25m, memory: 64Mi}
  limits: {cpu: 200m, memory: 256Mi}
