apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  labels:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: capitonic-platform
    app.kubernetes.io/managed-by: Helm
    capitonic.io/environment: dev
    capitonic.io/rollout-domain: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - {name: pgbouncer, port: 6432, targetPort: pgbouncer}
