apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: capitonic-platform
    app.kubernetes.io/managed-by: Helm
    capitonic.io/environment: dev
    capitonic.io/rollout-domain: monitoring
data:
  loki.yml: |-
{{ .Files.Get "assets/loki.yml" | nindent 4 }}
