apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ingester-strip-api
  labels:
    app.kubernetes.io/name: ingester-master
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: capitonic-platform
    app.kubernetes.io/managed-by: Helm
    capitonic.io/environment: dev
spec:
  stripPrefix:
    prefixes: [/api]
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingester-master
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-ingester-strip-api@kubernetescrd
  labels:
    app.kubernetes.io/name: ingester-master
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: capitonic-platform
    app.kubernetes.io/managed-by: Helm
    capitonic.io/environment: dev
spec:
  ingressClassName: traefik
  rules:
    - host: localhost
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ingester-master
                port: {name: http}
