apiVersion: v1
kind: PersistentVolume
metadata:
  name: capitonic-ingester-archives
  labels:
    app.kubernetes.io/name: ingester-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: capitonic-platform
    app.kubernetes.io/managed-by: Helm
    capitonic.io/environment: {{ $.Values.environment | quote }}
spec:
  capacity:
    storage: {{ .Values.archiveStorage.size | quote }}
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: {{ .Values.archiveStorage.path | quote }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ingester-archives
  labels:
    app.kubernetes.io/name: ingester-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: capitonic-platform
    app.kubernetes.io/managed-by: Helm
    capitonic.io/environment: {{ $.Values.environment | quote }}
spec:
  accessModes: [ReadWriteOnce]
  volumeMode: Filesystem
  storageClassName: ""
  volumeName: capitonic-ingester-archives
  resources:
    requests:
      storage: {{ .Values.archiveStorage.size | quote }}
