apiVersion: v1
kind: Service
metadata:
  name: ingester-worker
  labels:
    app.kubernetes.io/name: ingester-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: capitonic-platform
    app.kubernetes.io/managed-by: Helm
    capitonic.io/environment: {{ $.Values.environment | quote }}
    capitonic.io/rollout-domain: ingestion
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: ingester-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - {name: http, port: 8099, targetPort: http}
    - {name: grpc, port: 50051, targetPort: grpc}
