apiVersion: v1
kind: Service
metadata:
  name: timescaledb-headless
  labels:
    app.kubernetes.io/name: timescaledb
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: capitonic-platform
    app.kubernetes.io/managed-by: Helm
    capitonic.io/environment: {{ $.Values.environment | quote }}
    capitonic.io/rollout-domain: database
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: timescaledb
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - {name: postgres, port: 5432, targetPort: postgres}
    - {name: metrics, port: 9187, targetPort: metrics}
---
apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  labels:
    app.kubernetes.io/name: timescaledb
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: capitonic-platform
    app.kubernetes.io/managed-by: Helm
    capitonic.io/environment: {{ $.Values.environment | quote }}
    capitonic.io/rollout-domain: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: timescaledb
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - {name: postgres, port: 5432, targetPort: postgres}
    - {name: metrics, port: 9187, targetPort: metrics}
