image: capitonic/db-migrate:v0.3.0-rc.0
environment: development
imagePullPolicy: Never
imagePullSecrets: []
jobName: db-migrate
command: []
migrationsPattern: ""
postgresHost: timescaledb
resources:
  requests: {cpu: 100m, memory: 128Mi}
  limits: {cpu: 500m, memory: 512Mi}
